# Generated by Django 3.0.3 on 2020-04-09 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
    ]
