# Generated by Django 3.0.3 on 2020-04-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200410_0019'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='password1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
